<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\..\Engine\NativeUmm.Infrastructure\NativeUmm.Infrastructure.csproj" />
    <Compile Include="..\ADOFAIModManager.Windows\Application\Localization\*.cs" Link="Application\Localization\%(Filename)%(Extension)" />
    <Compile Include="..\ADOFAIModManager.Windows\Application\Catalog\*.cs" Link="Application\Catalog\%(Filename)%(Extension)" />
    <Compile Include="..\ADOFAIModManager.Windows\Infrastructure\Catalog\*.cs" Link="Infrastructure\Catalog\%(Filename)%(Extension)" />
    <Compile Include="..\ADOFAIModManager.Windows\Infrastructure\Localization\*.cs" Link="Infrastructure\Localization\%(Filename)%(Extension)" />
    <Compile Include="..\ADOFAIModManager.Windows\Infrastructure\Steam\*.cs" Link="Infrastructure\Steam\%(Filename)%(Extension)" />
    <EmbeddedResource Include="../ADOFAIModManager.Windows/Resources/Strings.*.json">
      <LogicalName>CoreChecks.Resources.%(Filename)%(Extension)</LogicalName>
      <WithCulture>false</WithCulture>
    </EmbeddedResource>
  </ItemGroup>
</Project>
