<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net10.0</TargetFramework>
    <AssemblyName>UMMInstallerEngine</AssemblyName>
    <RootNamespace>NativeUmm.Cli</RootNamespace>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <PublishAot>true</PublishAot>
    <SelfContained>true</SelfContained>
    <InvariantGlobalization>true</InvariantGlobalization>
    <StripSymbols>true</StripSymbols>
    <IlcGenerateStackTraceData>true</IlcGenerateStackTraceData>
    <SupportedOSPlatformVersion>14.0</SupportedOSPlatformVersion>
    <AppleMinOSVersion>14.0</AppleMinOSVersion>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\NativeUmm.Infrastructure\NativeUmm.Infrastructure.csproj" />
    <PackageReference Include="dnlib" Version="4.5.0" />
  </ItemGroup>
</Project>
