<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\NativeUmm.Application\NativeUmm.Application.csproj" />
    <PackageReference Include="dnlib" Version="4.5.0" />
  </ItemGroup>
</Project>
